/* 
 * PROYECTO 4CAPAS
 * AUTOR DAVID LLANES
 * FECHA 5 DE ABRIL DEL 2020
 * HERMOSILO, SONORA, MEXICO
*/

CREATE DATABASE PRACTICA_4_CAPAS
USE PRACTICA_4_CAPAS
GO

/*  ------------------------CATEGORIA FORM---------------------------   */

CREATE TABLE CATEGORIA(
	IDCATEGORIA INT IDENTITY(1, 1) PRIMARY KEY NOT NULL,
	CODIGO AS ('CT' + RIGHT ('00' + CONVERT(VARCHAR, IDCATEGORIA), (2))),
	NOMBRE NVARCHAR(30) NOT NULL, 
	DESCRIPCION NVARCHAR(256) NULL
)


INSERT INTO CATEGORIA VALUES('HERRAMIENTAS', 'LAS MEJORES HERRAMIENTAS')
INSERT INTO CATEGORIA VALUES('PINTURERIA', 'LAS MEJORES PINTURAS PARA TU CASA')

SELECT * FROM CATEGORIA


-- CONVERT(TIPO DATO, EXPRESION A CONVERTIR), (2) <-- NUMERO DE VECES QUE SE REPITE 00




---- PROCEDIMIENTO ALMACENADOS BUSCAR CATEGORIA
CREATE PROC SP_BUSCARCATEGORIA
	@BUSCAR NVARCHAR(20)
AS
SELECT * FROM CATEGORIA
WHERE NOMBRE LIKE @BUSCAR + '%'
-- '%' BUSCARA CUALQUIER LETRA PARECIDA


---- PROCEDIMIENTO ALMACENADO INSERTAR CATEGORIA
CREATE PROC SP_INSERTARCATEGORIA
	@NOMBRE NVARCHAR(30),
	@DESCRIPCION NVARCHAR(256)
AS 
INSERT INTO CATEGORIA VALUES (@NOMBRE, @DESCRIPCION)


--- PROCEDIMIENTO ALMACENADO EDITAR CATEGORIA
CREATE PROC SP_EDITARCATEGORIA
	@IDCATEGORIA INT,
	@NOMBRE NVARCHAR(30),
	@DESCRIPCION NVARCHAR(256)
AS
UPDATE CATEGORIA SET NOMBRE = @NOMBRE, DESCRIPCION = @DESCRIPCION 
WHERE IDCATEGORIA = @IDCATEGORIA


---- PROCEDIMINTO ALMACENADO ELIMINAR CATEGORIA
CREATE PROC SP_ELIMINARCATEGORIA
	@IDCATEGORIA INT
AS
DELETE CATEGORIA
WHERE IDCATEGORIA = @IDCATEGORIA


/*  ------------------------MARCA FORM---------------------------   */

USE PRACTICA_4_CAPAS
GO

CREATE TABLE MARCA(
	IDMARCA INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	CODIGO AS('MR' + RIGHT('00' + CONVERT(VARCHAR, IDMARCA), (2))),
	NOMBRE NVARCHAR(30) NOT NULL, 
	DESCRIPCION NVARCHAR(256) NULL
)

INSERT INTO MARCA VALUES ('TRUPPER','EQUIPO FERRETERO')


---- PROCEDIMIENTO ALMACENADO BUSCAR MARCA
CREATE PROCEDURE SP_BUSCARMARCA
	@BUSCAR NVARCHAR
AS
SELECT * FROM MARCA WHERE NOMBRE LIKE @BUSCAR + '%'

	EXEC SP_BUSCARMARCA TRU;


---- PROCEDIMIENTO ALMACENADO INSERTAR MARCA
CREATE PROCEDURE SP_INSERTARMARCA
	@NOMBRE NVARCHAR(30), 
	@DESCRIPCION NVARCHAR(256)
AS
INSERT INTO MARCA VALUES (@NOMBRE,@DESCRIPCION)

	EXEC SP_INSERTARMARCA 'DREAMHOUSE', 'EQUIPO PARA CONSTRUCCION';
	EXEC SP_INSERTARMARCA 'HOLSIM', 'CEMENTO PARA CONSTRUCCION';

---- PROCEDIMIENTO ALMACENADO EDITAR MARCA
CREATE PROCEDURE SP_EDITARMARCA
	@IDMARCA INT,
	@NOMBRE NVARCHAR(30),
	@DESCRIPCION NVARCHAR(256)
AS
UPDATE MARCA SET @NOMBRE = NOMBRE, @DESCRIPCION = DESCRIPCION
WHERE @IDMARCA = IDMARCA
	
	EXEC SP_EDITARMARCA 1, 'CEMEX', 'CEMENTOS MEXICANOS PARA LA CONSTRUCCION';


---- PROCEDIMIENTO ALMACENADO ELIMINAR MARCA
CREATE PROCEDURE SP_ELIMINARMARCA
	@IDMARCA INT
AS
DELETE MARCA WHERE @IDMARCA = IDMARCA
		
	EXEC SP_ELIMINARMARCA 2;













